### ISSUE TITLE
python-for-android 0.5 release checklist

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1043]
Pre-release:

- [x] Check that the current Android SDK works (it doesn't https://github.com/kivy/python-for-android/issues/1050)
- [x] Check outstanding issues for blockers (add to 0.5 milestone)
- [x] Check and merge PRs if possible (see especially https://github.com/kivy/python-for-android/milestone/1)
   - [x] gradle bootstrap - https://github.com/kivy/python-for-android/pull/1042
      - might be resolved by https://github.com/kivy/python-for-android/pull/1071
      - [x] for full fix, let's merge the bootstraps to use gradle or ant as appropriate/available
   - [x] ffpyplayer - https://github.com/kivy/python-for-android/pull/954
   - ~~[ ] numpy - https://github.com/kivy/python-for-android/issues/1074~~
   - [x] Fix the webview bootstrap
- [x] Fix the SDL2 launcher
- [x] Update version to 0.6
- [x] Write a changelog

Release!

- [x] Push the current state to the stable branch
- [x] Upload to pypi
- [x] Mailing list announcement
- [x] Blog post

**Comment by tito** [comment]
I suggest to move out SDL2/pygame launcher into a separate application, out of python-for-android. There is a way to make a launcher that start a kivy app from an entrypoint passed as an argument (with intent) instead of having a pure android app for that.

**Comment by inclement** [comment]
@tito I agree, it's one thing I wanted to explicitly address with pyonic interpreter (not to be 'the' app to do it, just as a test to add the right intent handling in p4a), but haven't got around to yet. KeyWeeUsr has got the launcher working fully with SDL2 expect for one bug relating to path handling, so I was going to fix that and have it available for now.

**Comment by inclement** [comment]
Update: https://github.com/kivy/python-for-android/pull/1071 seems to resolve the gradle build issue, but it's such a big change that it doesn't seem a good idea to push into a release without some staging. So, I now intend to check the launcher stuff and fix it if it's simple (which it should be), but there's nothing else holding things up.

**Comment by inclement** [comment]
With the last few fixes I pushed, and the merging of @KeyWeeUsr's sdl2 launcher fixes, everything seems to work for me. I want to take another look at the numpy recipe under crystax, but other than that I intend to do a release next weekend.

Following the release, I want to move quickly on merging the gradle fixes and looking at a couple of the other major things we're currently lacking. Hopefully we can do a further release relatively shortly, as there's plenty to move on.

**Comment by inclement** [comment]
Release complete!
