### ISSUE TITLE
0.6 release checklist

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1170]
All the recent big changes seem as stable as they're going to get with the amount of testing people give the master branch, so there seems no reason not to do another release.

Pre-release:

- [x] Check testapp builds with different SDK/NDK combinations
- [x] Check outstanding issues for blockers (add to 0.6 milestone)
  - [ ] Check/fix buildozer's apk copying bug
- [x] Check and merge PRs if possible
- [x] Update version to 0.6
- [ ] Write a changelog

Release!

- [x] Make the release
- [x] Push the current state to the stable branch
- [x] Upload to pypi
- [x] Mailing list announcement
- [x] Blog post
